name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build APK inside Isolated Kivy Container
      uses: subfuzion/kivy-buildozer-action@v1
      with:
        image: 'kivy/buildozer:latest'
        command: buildozer -v android debug

    - name: Upload APK Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
